---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-cainjector

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-cainjector

subjects:
  - kind: ServiceAccount
    name: cert-cainjector

...
