---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: cert-cainjector
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cainjector

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: cainjector

  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/component: cainjector

    spec:
      enableServiceLinks: false
      serviceAccountName: cert-cainjector

      securityContext:
        runAsNonRoot: true

      containers:
        - name: server
          image: cert-cainjector
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false

          args:
            - --v=2
            - --leader-election-namespace=$(POD_NAMESPACE)

          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

...
