---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: cert-manager-cainjector

spec:
  replicas: 1

  template:
    spec:
      serviceAccountName: cert-cainjector

      containers:
        - name: server
          image: cert-cainjector
          imagePullPolicy: Always

          args:
            - --v=2
            - --leader-election-namespace=$(POD_NAMESPACE)

          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

...
