---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml
  - deployment.yml

images:
  - name: cert-cainjector
    newName: quay.io/jetstack/cert-manager-cainjector
    newTag: "v1.14.5"

...
