---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: cert-cainjector:leaderelection
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cainjector

rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    resourceNames:
      - "cert-manager-cainjector-leader-election"
      - "cert-manager-cainjector-leader-election-core"
    verbs:
      - "get"
      - "update"
      - "patch"
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "create"

...
