---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: cert-cainjector:leaderelection

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-cainjector:leaderelection

subjects:
  - kind: ServiceAccount
    name: cert-cainjector

...
