---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: cert-cainjector:leaderelection
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cainjector

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-cainjector:leaderelection

subjects:
  - kind: ServiceAccount
    name: cert-cainjector

...
