---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: cert-webhook:subjectaccessreviews
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: webhook

rules:
  - apiGroups:
      - "authorization.k8s.io"
    resources:
      - "subjectaccessreviews"
    verbs:
      - "create"

...
