---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - role.yml
  - rolebinding.yml

  - service.yml
  - deployment.yml

  - mutatingwebhook.yml
  - validatingwebhook.yml

commonLabels:
  app.kubernetes.io/component: webhook

...
