---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml
  - service.yml
  - deployment.yml
  - mutatingwebhook.yml
  - validatingwebhook.yml

images:
  - name: cert-webhook
    newName: quay.io/jetstack/cert-manager-webhook
    newTag: "v1.18.0"

...
