---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration

metadata:
  name: cert-webhook
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: webhook
  annotations:
    cert-manager.io/inject-ca-from-secret: cert-manager/webhook-ca

webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: cert-webhook
        namespace: cert-manager
        path: /mutate
    failurePolicy: Fail
    name: webhook.cert-manager.io
    rules:
      - apiGroups:
          - cert-manager.io
          - acme.cert-manager.io
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "*/*"
    sideEffects: None
    timeoutSeconds: 10

...
