---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: cert-webhook:dynamic-serving
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: webhook

rules:
  - apiGroups:
      - ""
    resourceNames:
      - "webhook-ca"
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "create"

...
