---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: cert-webhook:dynamic-serving

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-webhook:dynamic-serving

subjects:
  - kind: ServiceAccount
    name: cert-webhook

...
