---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-issuers
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-issuers

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-clusterissuers
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-clusterissuers

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-certificates
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-certificates

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-orders
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-orders

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-challenges
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-challenges

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-ingress
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-ingress

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-manager-approve:cert-manager-io
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-approve:cert-manager-io

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-manager-certificatesigningrequests
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-certificatesigningrequests

subjects:
  - kind: ServiceAccount
    name: cert-manager

...

