---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-issuers

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-issuers

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-clusterissuers

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-clusterissuers

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-certificates

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-certificates

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-orders

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-orders

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-challenges

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-challenges

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: cert-ingress

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-ingress

subjects:
  - kind: ServiceAccount
    name: cert-manager

...
