---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller

  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/component: controller

    spec:
      enableServiceLinks: false
      serviceAccountName: cert-manager

      securityContext:
        runAsNonRoot: true

      containers:
        - name: server
          image: cert-controller
          imagePullPolicy: IfNotPresent

          args:
            - --v=2
            - --leader-election-namespace=$(POD_NAMESPACE)
            - --cluster-resource-namespace=$(POD_NAMESPACE)

          securityContext:
            allowPrivilegeEscalation: false

          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          ports:
            - name: http
              containerPort: 9402
              protocol: TCP

...
