---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml
  - service.yml
  - deployment.yml

images:
  - name: cert-controller
    newName: quay.io/jetstack/cert-manager-controller
    newTag: "v1.14.2"

...
